version: "3.3"

services:
  currency_conversion:
    image: "currency-conversion:latest"
    ports:
      - "8080:8080"
    environment:
      # Fixer API passed from environment file
      FIXER_API_KEY: "${FIXER_API_KEY}"
      SYNC_INTERVAL_MIN: "60"
      HTTP_PORT: "8080"
      # Uncomment to enable traces
      # TRACE: "1"
